### ISSUE TITLE
Integration with welleng

### ISSUE THREAD

**Issue by jonnymaserati** [Zabamund/wellpathpy#21]
Great work!

I've been working on something similar myself and there could be an opportunity to collaborate since I've coded up some stuff that you haven't yet? Specifically a start on well bore clearances (collision detection and separation factors) and generating new well paths.

https://github.com/jonnymaserati/welleng

**Comment by Zabamund** [comment]
Hi @jonnymaserati ! I actually saw your project in a linkedin post and it was mentioned to me by a friend in the software undergdound community (swu.ng/slack). 
We've slowed down development on this project as other obligations took over but I'm hopefull we'll be able to have a stable release before too long. 
The idea of this project is really to do one thing and one thing only, which is to handle deviations. So if there's a possibilty for collaboration on including this codebase into yours I'd be more than happy.
When we started this project some people were interested in anti-collision work too but that's beyond the scope of wellpathpy. So  I'll point them to your project instead.
