### ISSUE TITLE
No Coordinate Reference System

### ISSUE THREAD

**Issue by dmbaker** [Zabamund/wellpathpy#31]
There is no Coordinate Reference System defined for the azimuth readings.  Also, is the reference true north, a geographic reference system, or is the reference grid north, a Cartesian reference system?  
The surface_northing and surface_easting are meaningless without a CRS defined for them and the recorded azimuths.

**Comment by Zabamund** [comment]
CRS handling is out of scope for wellpathpy. Wellpathpy simply assumes a cartesian system with origin at 0, 0, 0.

**Comment by dmbaker** [comment]
@Zabamund, if Wellpathpy has CRS handling out of scope, then you should remove all references surface northings and eastings.  That way, the user is responsible for the azimuth reference used.  For example, if your surface coordinates, the surface_northing and surface_easting values, are reported in UTM CRS but your survey was recorded with a State Plane CRS, the mapped wellbore position will be very wrong.  It is better to have a coordinate free cubic reference system for Wellpathpy and leave it to the user to deal with the gird convergence issues.

**Comment by Zabamund** [comment]
Indeed CRS is out scope, if you feel this can be improved, please submit a patch.
