### ISSUE TITLE
TVD Values Can Be Non-Monotonic

### ISSUE THREAD

**Issue by dmbaker** [Zabamund/wellpathpy#32]
Many lateral wellbores have TVD values that overlap.  checkarrays_monotonic_tvd thus is wrong when enforcing monotonic TVD's.

**Comment by Zabamund** [comment]
Commit [a1cf6d6](https://github.com/Zabamund/wellpathpy/commit/a1cf6d6f3d0eac0a11f3b3b890fe96473c8acef0) agrees with this issue and fixes it.
The `checkarrays_monotonic_tvd` function was actually never used, but was indeed incorrect.
