### ISSUE TITLE
checkarrays - Inclination Check Error reports Wrong Range

### ISSUE THREAD

**Issue by dmbaker** [Zabamund/wellpathpy#33]
Current: 
```
if not ((0 <= inc) & (inc <= 180)).all():
        raise ValueError('all inc values must be in range 0-90')
```

should be:
```
if not ((0 <= inc) & (inc < 180)).all():
        raise ValueError('all inc values must be in range GTE 0 and LT 180')
```

First you report 90 not 180.  But more importantly, the inclination must be strictly less than 180 or PI.

**Comment by Zabamund** [comment]
Commit [cb09b2b](https://github.com/Zabamund/wellpathpy/commit/cb09b2b339e1cbc8da3d44e9fb35020007854df3) agrees with this issue and applies a correction as suggested.
