### ISSUE TITLE
Azimuth Must Be Strictly Less Than 360

### ISSUE THREAD

**Issue by dmbaker** [Zabamund/wellpathpy#34]
Current:
```
if not ((0 <= azi) & (azi <= 360)).all():
        raise ValueError('all azi values must be in range 0-360')
```

Should be:
```
if not ((0 <= azi) & (azi < 360)).all():
        raise ValueError('all azi values must be in range GTE 0 and LT 360')
```

**Comment by Zabamund** [comment]
Commit [022eb07](https://github.com/Zabamund/wellpathpy/commit/022eb078c15610f311ebeaa296ca7616c6bc8095) agrees with this issue and applies a fix as suggested.

**Comment by jonnymaserati** [comment]
Alternatively, you could use the modulo operator and avoid the risk of rasing an error completely:
```python
azi %= 360
```

**Comment by jokva** [comment]
That's semantically quite different - one (the error) signals that the input is probably bad, while the other silently accepts it.

**Comment by jonnymaserati** [comment]
It's not wrong, it's just not good practice. Could give a warning rather than breaking since it's a shame to waste some good compute?

**Comment by jokva** [comment]
Personally I think the right choice is to fail, and require data to be sanitized. It's not too bad for callers to do a % 360 either, and that way pipelines will fail rather than (somewhat quietly) warn should there be a problem.

Good practice is failing.

**Comment by jonnymaserati** [comment]
Agree that users should sanitize their own input data.
