### ISSUE TITLE
What's the rationale for having `pint` in here?

### ISSUE THREAD

**Issue by kwinkunks** [Zabamund/wellpathpy#45]
Pint doesn't seem to be doing much to earn its keep. Are there plans to incorporate unit conversion etc? 

If not, may I suggest dropping it from the requirements and letting the user worry about it?

If I have attached units to things, I think it should 'just work' -- maybe except where you strip them out in `convert.py`. (That module is 42 lines, but really just does a unit conversion, which is 1 line of code.)

**Comment by Zabamund** [comment]
Thank you Matt, PR #46 agrees with your issue and drops pint. Wellpathpy now only depends on numpy.
