### ISSUE TITLE
Adding deviation plot

### ISSUE THREAD

**Issue by AlexanderJuestel** [Zabamund/wellpathpy#67]
Hello @jokva,

would you guys be interested in having a function that plots the deviation data like in the plot below? (got some help from @endarthur)

Something along the lines of `pos.polar_plot()`or so? 

Or do you limit `wellpathpy` to reading deviation data and desurveying it?

![image](https://github.com/Zabamund/wellpathpy/assets/45469915/d4ddf924-d6b8-4a88-8775-5b5dc323edfb)

**Comment by jokva** [comment]
I think this is a feature that belongs in a separate project, if only to keep the dependency story good. Is it much code? I can imagine it being good in documentation.
