### ISSUE TITLE
m <-> ft conversion rounding error

### ISSUE THREAD

**Issue by AlexC84** [Zabamund/wellpathpy#7]
wellpathpy/test/test_location.py

Currently the m<->ft conversion uses 3.2808 which is 1/0.3048 rounded to 4dp and subsequently carries a rounding error. Suggest using 0.3048

**Comment by Zabamund** [comment]
Thank you for your issue @AlexC84 , I will check and correct asap.

**Comment by Zabamund** [comment]
made change as suggested, thank you @AlexC84 !
